apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailit.fullname" . }}-api
  labels:
    {{- include "mailit.labels" . | nindent 4 }}
    {{- include "mailit.api.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mailit.api.selectorLabels" . | nindent 4 }}
---
{{- if .Values.api.smtp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailit.fullname" . }}-smtp
  labels:
    {{- include "mailit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.smtp.service.type }}
  ports:
    - port: {{ .Values.api.smtp.service.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: {{ .Values.api.smtp.service.submissionPort }}
      targetPort: submission
      protocol: TCP
      name: submission
  selector:
    {{- include "mailit.api.selectorLabels" . | nindent 4 }}
{{- end }}
