apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailit.fullname" . }}-secrets
  labels:
    {{- include "mailit.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.jwtSecret }}
  jwt-secret: {{ .Values.auth.jwtSecret | b64enc }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
  {{- if .Values.dkim.masterEncryptionKey }}
  dkim-master-key: {{ .Values.dkim.masterEncryptionKey | b64enc }}
  {{- else }}
  dkim-master-key: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.password) }}
  postgres-password: {{ randAlphaNum 32 | b64enc }}
  {{- else if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc }}
  {{- else }}
  postgres-password: {{ .Values.postgresql.external.password | b64enc }}
  {{- end }}
  {{- if .Values.web }}
  nextauth-secret: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
